import "@/src/styles/globals.css";
import "react-loading-skeleton/dist/skeleton.css";

import localFont from "next/font/local";

const vazir = localFont({
    src: "../assets/Vazir.woff2",
    display: "swap",
});

export const metadata = {
    title: "Quiz App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    return (
        <html lang="fa-IR" dir="rtl" className={vazir.className}>
            <body>
              {children}
            </body>
        </html>
    );
}
